volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
mute: key(mute)
(play | media) next: key(next)
(play | media) previous: key(prev)
(play | pause): key(play)
