# volume up: key(volup)
# volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
(volume|media) mute: key(mute)
(play | media) next: key(next)
(play | media) previous: key(prev)
media (play | pause): key(play)
